[config]
schemaVersion = "0.0.1"

[package]
namespace = "PhantomGamers"
name = "StarsandUIARFix"
versionNumber = "1.0.2"
description = "BepInEx mod for Starsand to fix UI with aspect ratios other than 16:9"
websiteUrl = "https://github.com/PhantomGamers/StarsandUIARFix"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Starsand = "5.4.16"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "starsand" ]
categories = []